# Generated by Django 4.0.1 on 2023-07-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_tasks_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='date',
            field=models.DateField(default='1995-04-22'),
            preserve_default=False,
        ),
    ]
